### ISSUE TITLE
size limits in xgb.DMatrix

### ISSUE THREAD

**Issue by BlindApe** [tqchen/xgboost#156]
I'm trying to use xgb.DMatrix with 40.5M rows and 140 variables (dense matrix) and the process crash with a bad alloc memory message but I have more than double of RAM free at that time.
Could be a problem with internal array size?
Any tip?

**Comment by tqchen** [comment]
This is because internal data structure of the xgboost takes around 16 * n Bytes storage where n is number of non-missing elements in the matrix. In your case, it could be possible due to memory internal allocation failure. 

To scale to dataset of this scale and beyond, maybe you want to try the [distributed version](https://github.com/tqchen/xgboost/tree/master/multi-node)

Tianqi

**Comment by BlindApe** [comment]
Thank you. 

I thought 256Gb were enough for this, but probably I have a work around:

I have a binary variable and I'm using xgb.DMatrix with a dense data.frame, could I assign 0 to missing and save memory? Do the splitting works for this representation (the missing value is candidate for a split)?

**Comment by tqchen** [comment]
Yes you can definitely do that. This will also make training faster

On Monday, January 26, 2015, Blind Ape <notifications@github.com> wrote:

> Thank you.
>
> I thought 256Gb were enough for this, but probably I have a work around:
>
> I have a binary variable and I'm using xgb.DMatrix with a dense
> data.frame, could I assign 0 to missing and save memory? Do the splitting
> works for this representation (the missing value is candidate for a split)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tqchen/xgboost/issues/156#issuecomment-71543466>.
>


-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington

**Comment by tqchen** [comment]
The RAM should be enough.

This could due to the interfacing between R and xgb. There are some
duplicated copy going on.

Another work around is you save your data into libsvm format. xgb will
directly load from there and this could be more memory efficient.

Tianqi


Tianqi

On Monday, January 26, 2015, Blind Ape <notifications@github.com> wrote:

> Thank you.
>
> I thought 256Gb were enough for this, but probably I have a work around:
>
> I have a binary variable and I'm using xgb.DMatrix with a dense
> data.frame, could I assign 0 to missing and save memory? Do the splitting
> works for this representation (the missing value is candidate for a split)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tqchen/xgboost/issues/156#issuecomment-71543466>.
>


-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington

**Comment by BlindApe** [comment]
Using:
https://github.com/zygmuntz/r-libsvm-format-read-write/blob/master/f_write.libsvm.r

The 40M transformation will take 17 days...

Thank you for the tip anyway

**Comment by hetong007** [comment]
@BlindApe I think using pure R to do the transformation is unwise. If you have the original data in csv format on your hardriver, then using cpp/python could be much faster.

**Comment by BlindApe** [comment]
Thank you, Tong.

Data are heavy preprocessed with data.table so I've tried to write to csv from R and is very very slow too.
I've taken a look to the parsers and think sparse matrix format is a bit more efficient even in non sparse matrices. The matrix parser define data as array n x p and for sparse of size is the non missing values.

Do you think using sparse parser even in non sparse data (less than 10 % of missings) could help?

I'm running now sparse.model.matrix. It is a bit faster than write the csv.

**Comment by hetong007** [comment]
@BlindApe I am not sure about the performance, but I guess it might be better not to use sparse structure due to the __non-sparsity__ of this matrix. In this situation the sparse format might need even more space for storing the values **along with the indices**.

Do you accept the following solution?

1. Use `write.table` to dump the data to hard disk. This should be much faster than applying `writeline` to each single row.
2. Use other tools to transform it in libsvm format. [libsvm officially provides such tools](http://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#f307).

@tqchen Have we talked about the issue that loading csv/tsv/space-s-v files to DMatrix directly before? May I know reasons for not having this function? Thanks.

**Comment by tqchen** [comment]
@hetong007 we can support direct loading of csv/tsv for purely numerical matrices.

**Comment by BlindApe** [comment]
@hetong007 
I'll try tomorrow.

But I think there is something more. When I call xgb.DMatrix the used RAM is only 26 Gb. There is 230 Gb free. And the process crash inmediately.

The size of matrix now is 40,000,000 x 75 = 3,000,000,000

The line in XGDMatrixCreateFromMat_R function:

std::vector<float> data(nrow * ncol);

Could be possible the problem isn't memory but the index range of data?

**Comment by hetong007** [comment]
@BlindApe Good point! Integer overflow.

@tqchen Do you think using `long long`/`int64` here is acceptable?

**Comment by tqchen** [comment]
I pushed a fix on this, please try again. Thanks for pointing it out

**Comment by BlindApe** [comment]
I'll do tomorrow. Here is 1:30 AM.
I think you fixed the problem!
Thank you @tqchen @hetong007

**Comment by BlindApe** [comment]
I confirm you this works!
Thank you again.

**Comment by tqchen** [comment]
Thank you for bringing out the issue! It is great to have users like you to push the limit of the toolkit and  make it better

**Comment by BlindApe** [comment]
Seems I've reached the limit again:
With a dense matrix of  4,649,331,205 elements ( aprox. 40M x 115 columns) the process crash, but with  4,083,325,667 elements runs fine. The amount of RAM in second case in alwas lower than 100Gb of 256 Gb. The first case crash when using 55 Gb inmediately the call
std::vector data(nrow * ncol) of  XGDMatrixCreateFromMat_R function.

@tqchen,  Which is the theoric max index of an array with the last mod you done?

Internal representation of data is reached earliest the tool limits: In second case runs fine with 60 Gb after the process finish the matrix transposition.

**Comment by tqchen** [comment]
I think this could be the problem of defined size of the matrix. unsigned long was supposed to be 64 bit but maybe interpreted as 32 bit on your machine.

I made a fix on this and try if things works better

**Comment by BlindApe** [comment]
This could be, the max int with 32 bits is 4,294 M and explains the behavior.
I run Windows 8.1 Pro 64 bits, with R 3.1.2. 64 bits.

Thank you @tqchen

**Comment by BlindApe** [comment]
Sorry for the delay, but I've fitting some extra slow models and didn't finished until now.

I confirm you the last fix works!

I'm running 40M rows x  157 features (> 6000M of elements, so indexing 64 bit works).
The peak of RAM was 180 Gb in the xgb.DMatrix transposing. After the fitting begins, the process runs in 40 threads with only 80 Gb of RAM.
So, xgb.DMatrix is currently the bottleneck. 
For your info, the process never uses more than 65%-70% of CPU (?!)

Thank you!

**Comment by tqchen** [comment]
Thanks! In the division strategy, nsize=#feature=157 in your case, so in your case we do use one per column. The CPU rate could due to imbalance of computation. 

Tianqi
